# Generated by Django 2.2.4 on 2020-04-02 16:08

from django.db import migrations

def new_building_check(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.construction_year <= 2015:
            flat.new_building = False
        else:
            flat.new_building = True
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20200401_2111'),
    ]

    operations = [
        migrations.RunPython(new_building_check)
    ]
