# Generated by Django 2.2.4 on 2020-04-04 19:12

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20200404_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='pure_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region=None, verbose_name='Нормализованный номер владельца'),
        ),
    ]
