# Generated by Django 2.2.4 on 2020-04-10 20:01

from django.db import migrations

def parse_flats_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        this_flat_owner = Owner.objects.get(owner=flat.owner)
        this_flat_owner.flats_owned.add(flat.id) 

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20200408_2011'),
    ]

    operations = [
    migrations.RunPython(parse_flats_to_owners)
    ]
