# Generated by Django 2.2.4 on 2020-05-06 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_auto_20200505_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatreport',
            name='flat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flat_reports', to='property.Flat', verbose_name='Квартира, на которую пожаловались'),
        ),
        migrations.AlterField(
            model_name='flatreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_flats', to=settings.AUTH_USER_MODEL, verbose_name='Кто жаловался'),
        ),
    ]
