# Generated by Django 2.2.4 on 2020-05-06 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_auto_20200506_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flatreport',
            old_name='user',
            new_name='reported_user',
        ),
    ]
