# Generated by Django 2.2.4 on 2020-05-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_auto_20200506_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owners_phonenumber',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Номер владельца'),
        ),
    ]
