# Generated by Django 2.2.4 on 2020-05-14 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_auto_20200514_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatreport',
            name='reported_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flat_reports', to=settings.AUTH_USER_MODEL, verbose_name='Кто жаловался'),
        ),
    ]
